- hosts: nav_nav_1
  connection: docker
  vars_files:
    - [ 'secret.yml', 'vars.yml']
    
  vars:
    - tm_password: '<put-secret-password-here>'
    - python_version: 2.7
  tasks:
    - name: Create dir
      file:
        path: /etc/nav/python
        state: directory
        
    - name: Create local_settings.py
      template:
        src: local_settings.py.j2
        dest: /etc/nav/python/local_settings.py
      notify: Restart apache
               
    - name: Hint about setting password
      debug:
        msg: "NB-NB ==== Remember to edit /tmsource/local_settings.py === NB-NB"
      when: tm_password == '<put-secret-password-here>'

    - name: Install packages (apt)
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python-sqlalchemy
      notify: Restart apache
      
    - name: Install packages (PIP)
      pip:
        name: "{{ item }}"
      with_items:
        - pymssql
      notify: Restart apache
      
    - name: Fix Python include path
      lineinfile:
        dest: /etc/python{{ python_version }}/sitecustomize.py
        line: "import sys; sys.path.append('/tmsource')"
      notify: Restart web

    - name: Symlink local_urls.py
      file:
        src: /tmsource/local_urls.py
        dest: /etc/nav/python/local_urls.py
        state: link
        

  handlers:
    - name: Restart apache
      command: supervisorctl restart apache2
