---

- hosts: localhost

  tasks:
    - name: Clean slate, remove all imported roles
      file:
        path: .imported_roles
        state: absent
    
    - name: Install all required roles into ./.imported_roles
      local_action:
        command ansible-galaxy -vvvv install -r requirements.yml --roles-path .imported_roles

    - name: Ensure that ./imported_roles is ignored by git
      lineinfile:
        dest:   ../.gitignore
        regexp: '^\/.imported_roles$'
        line:   '/.imported_roles'
        state:  present

    - name: Ensure that ./.imported_roles is included into roles_path
      ini_file:
        dest:   ./ansible.cfg
        section: default
        option: roles_path
        value:   './roles:./.imported_roles'
        state:  present

